/*
 * Word lists for Wordle (Open Arcade). Generated; do not edit by hand.
 *
 * ANSWERS (2333 words): a curated list of common five-letter English words.
 *   Built from the most common levels (10-35) of SCOWL, minus regular
 *   plurals, -ed forms, odd comparatives, slang and anything crude or
 *   loaded, plus a hand-picked set of familiar words. It is not the NYT list.
 *
 * GUESSES (6453 more words, 8786 accepted in total): every answer, plus the
 *   five-letter words of the ENABLE word list (public domain) and of SCOWL
 *   levels 10-70, with slurs and strong profanity removed.
 *
 * SCOWL (Spell Checker Oriented Word Lists), http://wordlist.aspell.net/
 *   Copyright 2000-2018 by Kevin Atkinson
 *
 *   Permission to use, copy, modify, distribute and sell these word
 *   lists, the associated scripts, the output created from the scripts,
 *   and its documentation for any purpose is hereby granted without fee,
 *   provided that the above copyright notice appears in all copies and
 *   that both that copyright notice and this permission notice appear in
 *   supporting documentation. Kevin Atkinson makes no representations
 *   about the suitability of this array for any purpose. It is provided
 *   "as is" without express or implied warranty.
 *
 * ENABLE (Enhanced North American Benchmark LExicon) is in the public domain.
 */
(function (root) {
  'use strict';

  var ANSWERS = (
    'aback abate abbey abbot abhor abide abode abort about above abuse abuzz abyss acorn acrid actor ' +
    'acute adage adapt adder adept adieu admit adobe adopt adore adorn adult aegis affix afire afoot ' +
    'after again agape agate agave agent agile aging aglow agony agree ahead aisle alarm album alder ' +
    'alert algae alias alibi alien align alike alive allay alley allot allow alloy aloft aloha alone ' +
    'along aloof aloud alpha altar alter amass amaze amber amble amend amigo amino amiss amity among ' +
    'amour ample amply amuse angel anger angle angry angst anime anise ankle annex annoy annul anode ' +
    'antic anvil aorta apart aphid apple apply apron aptly arbor ardor arena argon argue arise armor ' +
    'aroma arose array arrow arson artsy ascot ashen aside askew aspen assay asset aster atlas atoll ' +
    'atone attic audio audit auger augur aural avail avert avian avoid await awake award aware awash ' +
    'awful awoke axial axiom azure bacon badge badly bagel baggy baker balmy balsa banal banjo barge ' +
    'baron basic basil basin basis baste batch bathe batik baton batty bayou beach beady beard beast ' +
    'bebop beech beefy befit began begin begun beige being belch belie belle belly below bench bendy ' +
    'beret berry berth beryl beset bevel bezel bible biker bilge binge bingo biome biped birch birth ' +
    'bison bitty black blade blame bland blank blare blast blaze bleak bleat bleep blend bless blimp ' +
    'blind blink bliss blitz bloat block blond blood bloom blown bluff blunt blurb blurt blush board ' +
    'boast bogey bogus bongo bonus boost booth booze boozy borax borne boron bossy botch bough bound ' +
    'bowel boxer brace braid brain brake brand brash brass brave bravo brawl brawn bread break briar ' +
    'bribe brick bride brief brine bring brink briny brisk broad broil broke brood brook broom broth ' +
    'brown brunt brush brute buddy budge buggy bugle build built bulge bulky bully bumpy bunch bunny ' +
    'burly burnt burst bushy butte buyer bylaw byway cabal cabin cable cacao cache cacti cadet cadre ' +
    'cagey cairn calve calyx camel cameo campy canal candy canny canoe canon canto caper carat cargo ' +
    'carob carol carry carve caste catch cater catty caulk cause cease cedar cello chafe chaff chain ' +
    'chair chalk champ chant chaos chard charm chart chase chasm cheap cheat check cheek cheep cheer ' +
    'chess chest chewy chick chide chief child chili chill chime chimp china chino chirp chive choir ' +
    'choke chomp chord chore chose chuck chump chunk churn chute cider cigar cinch circa civic civil ' +
    'clack claim clamp clang clank clash clasp class clean clear cleat cleft clerk click cliff climb ' +
    'clime cling clink cloak clock clone close cloth cloud clout clove clown cluck clump clung clunk ' +
    'coach coast cobra cocoa codex colic colon color combo comet comfy comic comma conch condo conga ' +
    'conic copse coral corgi corny corps couch cough could count coupe court coven cover covet cower ' +
    'crack craft cramp crane crank crash crass crate crave crawl craze crazy creak cream creed creek ' +
    'creep crepe crept cress crest crime crimp crisp croak crock crone crony crook croon cross crowd ' +
    'crown crude cruel crumb crush crust crypt cubic cubit cumin cupid curio curly curry curse curve ' +
    'curvy cushy cutie cycle cynic dacha daddy daffy daily dairy daisy dally dance dandy daunt dealt ' +
    'death debit debug debut decaf decal decay decor decoy decry defer deify deign deity delay delta ' +
    'delve demon denim dense depot depth derby deter detox deuce devil diary dicey digit dimly diner ' +
    'dingo dingy diode dirge dirty disco ditch ditto ditty divan diver divot divvy dizzy dodge dodgy ' +
    'doggy dogma doily doing dolly donor donut dopey dorky dotty doubt dough douse dowdy dowel downy ' +
    'dowry dozen draft drain drake drama drank drape drawl drawn dread dream dress drift drill drink ' +
    'drive droll drone drool droop dross drove drown druid drunk dryad dryer dryly ducal ducat duchy ' +
    'dummy dumpy dunce dusky dusty duvet dwarf dweeb dwell dwelt dying eager eagle early earth easel ' +
    'eaten eater ebony edict eerie egret eight eject elate elbow elder elect elegy elfin elite elope ' +
    'elude email embed ember emcee emoji emote empty enact endow enemy enjoy ennui ensue enter entry ' +
    'envoy epoch epoxy equal equip erase erect erode error erupt essay ester ether ethic ethos evade ' +
    'event every evict evoke exact exalt excel exert exile exist expat expel extol extra exude exult ' +
    'fable facet faint fairy faith false fancy farce fatal fault fauna favor feast feign feint felon ' +
    'femur fence feral ferry fetal fetch fetid fetus fever fewer fiber field fiend fiery fifth fifty ' +
    'fight filch filly filmy filth final finch first fishy fixer fizzy fjord flail flair flake flaky ' +
    'flame flank flare flash flask fleck fleet flesh flick flier fling flint flirt float flock flood ' +
    'floor flora floss flour flout flown fluff fluid fluke flume flung flunk flush flute flyby flyer ' +
    'foamy focal focus foggy foist folio folly foray force forge forgo forte forth forty forum found ' +
    'fount foyer frail frame franc frank fraud freak fresh friar frill frisk frizz frock frond front ' +
    'frost froth frown froze fruit frump fryer fudge fugue fully fungi funky funny furor furry fussy ' +
    'futon fuzzy gabby gable gaffe gaily gamer gamma gamut gassy gaudy gauge gaunt gauze gauzy gavel ' +
    'gawky gecko geeky geese genie genre genus geode getup ghost ghoul giant giddy girth given gizmo ' +
    'glade gland glare glass glaze gleam glean glide glint glitz gloat globe gloom glory gloss glove ' +
    'gluey glyph gnarl gnash gnome godly gofer going golly goner goody gooey goofy goose gorge gorse ' +
    'gouge gourd grace grade graft grail grain grand grant grape graph grasp grass grate grave gravy ' +
    'graze great grebe green greet grief grill grime grimy grind gripe groan groin groom grope gross ' +
    'group grout grove growl grown gruel gruff grunt guano guard guava guess guest guide guild guile ' +
    'guilt guise gulch gully gumbo gummy guppy gushy gusto gusty gutsy habit haiku hairy halve hammy ' +
    'handy happy hardy harpy harsh haste hasty hatch hater haunt haven havoc hazel heady heard heart ' +
    'heath heave heavy hedge hefty heist helix hello hence henna heron hertz hiker hilly hinge hippo ' +
    'hitch hoard hobby hoist hokey holly homer homey honey honor hooky horde horse hotel hotly hound ' +
    'house hovel hover howdy hubby huffy human humid humor humph humus hunch hurry husky hutch hydra ' +
    'hyena hyper icily icing ideal idiom idler idyll igloo image imbue impel imply inane inbox incur ' +
    'index inept inert infer ingot inlay inlet inner input inset intel ionic irate irony islet issue ' +
    'itchy ivory jaunt jazzy jelly jerky jetty jewel jiffy jimmy joint joist joker jolly joule joust ' +
    'judge juice juicy julep jumbo jumpy junta juror kapok kaput karma kayak kazoo kebab khaki kiddo ' +
    'kiosk kitty klutz knack knave knead kneel knell knelt knife knock knoll known koala kooky krill ' +
    'kudos kudzu label labor laden ladle lager lance lanky lapel lapse larch large largo larva laser ' +
    'lasso latch later latex lathe latte laugh layer leach leafy leaky leapt learn lease leash least ' +
    'leave ledge leech leery lefty legal leggy legit lemon lemur leper levee level lever libel liege ' +
    'light liken lilac limbo limit linen liner lingo lipid liter lithe liven liver livid llama loamy ' +
    'loath lobby local locus lodge lofty logic login loner loopy loose loser lotto lotus louse lousy ' +
    'lover lower lowly loyal lucid lucky lumpy lunar lunch lunge lurch lurid lying lymph lyric macaw ' +
    'macho macro madam madly magic magma maize major maker mambo manga mange mango mangy mania manic ' +
    'manly manna manor maple march marry marsh mason match matte matzo mauve maven maxim maybe mayor ' +
    'mealy meant meaty medal media medic melee melon mercy merge merit merry messy metal meter metro ' +
    'micro midge midst might milky mimic mince miner minor minty minus mirth miser misty mixer mocha ' +
    'modal model modem mogul moist molar moldy mommy money month mooch moody moose moral moray morph ' +
    'mosey mossy motel motif motor motto mound mount mourn mouse mousy mouth mover movie mower mucky ' +
    'muddy muggy mulch mummy munch mural murky mushy music musky musty myrrh nacho nadir naive naked ' +
    'nanny nasal nasty natal natty naval navel needy neigh nerdy nerve nervy never newly nexus niche ' +
    'niece nifty night ninja ninth nippy noble nobly noise noisy nomad noose north notch novel nudge ' +
    'nurse nutty nylon nymph oaken oasis obese occur ocean octet oddly offal offer often okapi olden ' +
    'older oldie olive omega onion onset opera opine optic orate orbit order organ other otter ought ' +
    'ounce outdo outer overt owlet owner oxbow oxide ozone pacer padre pagan pager paint panda panel ' +
    'panic papal paper parch parka parry parse party pasta paste pasty patch patio patsy patty pause ' +
    'payee payer peace peach pearl pecan pedal peeve penal pence penne penny peony peppy perch peril ' +
    'perky pesky pesto petal petty phase phone phony photo piano picky piece piety piggy pilaf pilot ' +
    'pinch pinky pinto pious piper pitch pithy piton pivot pixel pixie pizza place plaid plain plait ' +
    'plane plank plant plate plaza plead pleat pluck plumb plume plump plunk plush poach point poise ' +
    'poker polar polio polka polyp pooch poppy porch poser posit posse pouch pound power prank prawn ' +
    'preen press price pride prime primp print prior prism privy prize probe promo prone prong proof ' +
    'prose proud prove prowl proxy prude prune psalm pudgy puffy pulpy pulse punch pupil puppy puree ' +
    'purge purse pushy putty pylon quack quaff quail quake qualm quark quart quash queen quell query ' +
    'quest queue quick quiet quill quilt quirk quite quota quote rabbi rabid racer radar radio radon ' +
    'rainy raise rally ramen ranch range rapid raspy ratio ratty ravel raven rayon razor reach react ' +
    'ready realm rebel rebus rebut recap recur reedy refer refit regal rehab reign relax relay relic ' +
    'remit remix renal renew repay repel reply rerun reset resin retch retro retry reuse revel revue ' +
    'rhino rhyme rider ridge rifle right rigid rigor rinse ripen risen riser risky ritzy rival river ' +
    'rivet roach roast robin robot rocky rodeo rogue roomy roost rotor rouge rough round rouse route ' +
    'rover rowdy rower royal ruble ruddy rugby ruler rumba rummy rumor runny rupee rural rusty saber ' +
    'sable sadly saint salad salon salsa salty salve salvo samba sandy sappy sarge sassy satay satin ' +
    'sauce saucy sauna saver savor savvy scald scale scalp scaly scamp scant scare scarf scary scene ' +
    'scent scion scoff scold scone scoop scoot scope score scorn scour scout scowl scram scrap screw ' +
    'scrub scrum scuba scuff sedan seedy segue seize sense sepia serge serif serum serve setup seven ' +
    'sever sewer shack shade shady shaft shake shaky shale shall shame shank shape shard share shark ' +
    'sharp shave shawl sheaf shear sheen sheep sheer sheet sheik shelf shell shift shill shine shiny ' +
    'shire shirk shirt shoal shock shone shook shoot shore short shout shove shown showy shred shrew ' +
    'shrub shrug shuck shunt shush sidle siege sieve sight sigma silky silly since sinew singe sinus ' +
    'siren sitar sixth sixty skate skein skier skiff skill skimp skirt skulk skull skunk slack slain ' +
    'slake slang slant slash slate sleek sleep sleet slept slice slick slide slime slimy sling slink ' +
    'sloop slope slosh sloth slump slung slunk slurp slush slyly smack small smart smash smear smell ' +
    'smelt smile smirk smite smith smock smoke smoky snack snafu snail snake snare snarl sneak sneer ' +
    'snide sniff snipe snoop snore snort snout snowy snuff soapy sober softy soggy solar solid solve ' +
    'sonar sonic sooty sorry sound soupy south space spade spare spark spasm spate spawn speak spear ' +
    'speck speed spell spend spent spice spicy spiel spike spiky spill spine spiny spire spite splat ' +
    'split spoil spoke spoof spool spoon spore sport spout spray spree sprig spurn spurt squad squat ' +
    'squid stack staff stage staid stain stair stake stale stalk stall stamp stand stank stare stark ' +
    'start stash state stave steak steal steam steed steel steep steer stein stent stern stick stiff ' +
    'still stilt sting stink stint stoat stock stoic stoke stole stomp stone stony stood stool stoop ' +
    'store stork storm story stout stove strap straw stray strep strew strip strum strut stuck study ' +
    'stuff stump stung stunk stunt style suave sudsy suede sugar suite sulky sully sumac sunny super ' +
    'surge surly sushi swamp swank swarm swath swear sweat sweep sweet swell swept swift swill swine ' +
    'swing swipe swirl swish swoon swoop sword swore sworn swung syrup tabby table taboo tacit tacky ' +
    'taffy taint taken taker tally talon tamer tango tangy taper tapir tardy tarot tarry taste tasty ' +
    'tatty taunt taupe tawny teach teary tease teddy teeny teeth tempo tempt tenet tenor tense tenth ' +
    'tepid terse testy thank theft their theme there these theta thick thief thigh thing think third ' +
    'thorn those three threw throb throe throw thumb thump thyme tiara tibia tidal tiger tight timer ' +
    'timid tinge tinny tipsy titan tithe title tizzy toady toast today toddy token tonal toner tonic ' +
    'tonne tooth topaz topic torch torso torte torus total totem touch tough towel tower toxic toxin ' +
    'trace track tract trade trail train trait tramp trash trawl tread treat trend triad trial tribe ' +
    'trick trike trill tripe trite troll troop trope trout trove truce truck truly trump trunk truss ' +
    'trust truth tryst tubby tuber tulip tulle tummy tuner tunic tutor twang tweak tweed tweet twerp ' +
    'twice twill twine twirl twist tying udder ulcer ultra umbra uncap uncle uncut under undue unfit ' +
    'unify union unite unity unlit unpin untie until unwed unzip upend upper upset urban usage usher ' +
    'using usual usurp usury utter vague valet valid valor value valve vapid vapor vault vaunt vegan ' +
    'venal venom venue verge verse verve vicar video vigil vigor villa vinyl viola viper viral virus ' +
    'visit visor vista vital vivid vocal vodka vogue voice voila voter vouch vowel vying wacky wader ' +
    'wafer wager wagon waist waive waken waltz warty waste watch water waver waxen weary weave wedge ' +
    'weedy weepy weigh weird whack whale wharf wheat wheel whelp where which whiff while whine whiny ' +
    'whirl whisk white whole whoop whose widen widow width wield wimpy wince winch windy wiper wiser ' +
    'wispy witch witty woken woman women woody woozy wordy world wormy worry worse worst worth would ' +
    'wound woven wrath wreak wreck wrest wring wrist write wrong wrote wrung wryly xenon yacht yearn ' +
    'yeast yield yodel yokel young youth yucca yucky yummy zebra zesty zilch zippy'
  ).split(' ');

  var GUESSES = (
    'aahed aalii aargh abaca abaci abaft abaka abamp abase abash abbas abbes abeam abele abets abies ' +
    'abler ables abmho abohm aboil aboma aboon abris abuts abyes abysm acari acerb aceta ached aches ' +
    'achoo acids acidy acing acini ackee acmes acmic acned acnes acock acold acred acres acted actin ' +
    'acyls addax added addle adeem adios adits adman admen admix adobo adown adoze adunc adust adyta ' +
    'adzes aecia aedes aeons aerie afars afore afoul afrit agama agars agaze agene agers agger aggie ' +
    'aggro aghas agios agism agist agita aglee aglet agley agmas agone agons agora agria agues ahold ' +
    'ahull aided aider aides ailed aimed aimer aioli aired airer airns airth airts aitch aiver ajiva ' +
    'ajuga akees akela akene alack alamo aland alane alang alans alant alary alate albas alcid aldol ' +
    'alecs alefs aleph alfas algal algas algid algin algor algum alifs aline alist aliya alkyd alkyl ' +
    'allee allod allyl almah almas almeh almes almud almug aloes aloin altho altos alula alums alway ' +
    'amahs amain ambit ambos ambry ameba ameer amens ament amias amice amici amide amido amids amies ' +
    'amiga amine amins amirs ammos amnia amnic amnio amoks amole amort ampul amuck amyls ancon anear ' +
    'anele anent angas anile anils anima animi anion ankhs ankus anlas annal annas anoas anole anomy ' +
    'anons ansae antae antas anted antes antis antra antre antsy apace apeak apeek apers apery aphis ' +
    'apian aping apish apnea apods aport appal appel apres apses apsis apter aquae aquas araks arced ' +
    'arcus ardeb areae areal areas areca areic arete argal argil argle argol argot argus arhat arias ' +
    'ariel arils arles armed armer armet aroid arpen arras arris arsis artal artel arums arval arvos ' +
    'aryls asana ascus asdic ashed ashes asked asker askoi askos asper aspic aspis assai asses astir ' +
    'asyla ataps ataxy atilt atman atmas atoms atomy atony atopy atria atrip attar audad aught aulic ' +
    'aulos aunts aunty aurae aurar auras aurei aures auric auris aurum autos auxin avant avast avens ' +
    'avers avgas avion aviso avows awing awned awols axels axile axils axing axion axite axled axles ' +
    'axman axmen axone axons ayahs ayins azans azide azido azine azlon azoic azole azons azote azoth ' +
    'baaed baals babas babel babes babka baboo babul babus bacca baccy backs baddy baels baffs baffy ' +
    'bahts bails bairn baith baits baiza baize baked bakes balas balds baldy baled baler bales balks ' +
    'balky balls bally balms banco bands bandy baned banes bangs banks banns banty barbe barbs barde ' +
    'bards bared barer bares barfs baric barks barky barms barmy barns barny barre barye basal based ' +
    'baser bases basks bassi basso bassy basts bated bates baths batts battu bauds baulk bawds bawdy ' +
    'bawls bawty bayed bazar bazoo beads beaks beaky beams beamy beano beans bears beats beaus beaut ' +
    'beaux becap becks bedel bedew bedim beefs beeps beers beery beets befog begat beget begot begum ' +
    'beigy belay belga bells belts bemas bemix bends benes benne benni benny bents bergs berks berme ' +
    'berms besom besot bests betas betel beths beton betta bevor bevvy bewig bezil bhaji bhang bhoot ' +
    'bhuts biali bialy bibbs bicep bices biddy bided bider bides bidet bield biers biffs biffy bifid ' +
    'bight bigly bigot bijou biked bikes bikie bilbo biles bilgy bilks bills billy bimah bimas binal ' +
    'bindi binds bines binit bints biont biota bipod birds birks birle birls birrs birse bises bisks ' +
    'biter bites bitsy bitts bizes blabs blags blahs blain blams blase blate blats blawn blaws blear ' +
    'blebs bleed blent blest blets blimy bling blini blips blite blobs blocs blogs bloke bloop blots ' +
    'blows blowy blubs blued bluer blues bluet bluey blume blurs blype boars boart boats bobby bocce ' +
    'bocci boche bocks boded bodes bodge boffo boffs bogan boggy bogie bogle bohea boils boing boite ' +
    'bolar bolas bolds boles bolls bolos bolts bolus bombe bombs bonce bonds boned boner bones boney ' +
    'bongs bonks bonne bonny bonze booby booed boogy books booms boomy boons boors boots booty borak ' +
    'boral boras bored borer bores boric borts borty bortz bosks bosky bosom boson bosun botas botel ' +
    'bothy botts boule bourg bourn bouse bousy bouts bovid bowed bower bowls bowse boxed boxes boyar ' +
    'boyla boyos bozos brach bract brads braes brags brail braky brank brans brant brats brava bravi ' +
    'braws braxy brays braza braze bream brede breed brees brens brent breve brews brier bries brigs ' +
    'brill brims brins brios brits britt broch brock brome bromo bronc broos brose brosy brows brugh ' +
    'bruin bruit brume brusk bubal bubba bubby bucko bucks bueno buffi buffo buffs buffy buhls buhrs ' +
    'bulbs bulgy bulks bulla bulls bumfs bumph bumps bunco bunds bundt bungs bunko bunks bunns bunts ' +
    'bunya buoys buran buras burbs burds buret burgh burgs burin burka burke burls burns burps burqa ' +
    'burro burrs burry bursa burse busby bused buses busks busts busty butch buteo butle butts butty ' +
    'butut butyl buxom bwana byres byrls byssi bytes cabby caber cabob cacas caddy cades cadge cadgy ' +
    'cadis caeca cafes caffs caged cager cages cahow caids cains caird cajon caked cakes cakey calfs ' +
    'calif calix calks calla calls calms camas cames campi campo camps caned caner canes canid canna ' +
    'canso canst cants canty caped capes caphs capon capos caput carbo carbs cards cared carer cares ' +
    'caret carex carks carle carls carns carny carom carpi carps carrs carse carte carts casas cased ' +
    'cases casks casky casts casus cates cauda cauld cauls caved caver caves cavie cavil cawed cebid ' +
    'cecal cecum ceded ceder cedes cedis ceiba ceils celeb cella celli cells celom celts cense cento ' +
    'cents ceorl cepes cerci cered ceres ceria ceric ceros certs cesar cesta cesti cetes chads chams ' +
    'chang chape chaps chapt chare chark charr chars chary chats chaws chays chefs chela chemo chert ' +
    'cheth chevy chews chiao chias chico chics chiel chile chimb chine ching chins chips chirk chirm ' +
    'chiro chirr chits chivy chock chocs choky choli chook chops chott chows chubs chufa chuff chugs ' +
    'chums churl churr chyle chyme ciaos cibol cilia cimex cines cions cires cirri cisco cissy cists ' +
    'cited citer cites civet civie civvy clach clade clads clags clams clans claps clapt claro clary ' +
    'clast clave clavi claws clays cleek clefs clepe clept clews clift cline clips clipt clods clogs ' +
    'clomb clomp clonk clons cloot clops clots clour cloys cloze clubs clued clues coact coala coals ' +
    'coaly coapt coati coats cobbs cobby cobia coble cocas cocci cocky cocos codas codec coded coden ' +
    'coder codes codon coeds coffs cogon cohog cohos coifs coign coils coins coirs coked cokes colas ' +
    'colds coled coles coley colin colly colog colts colza comae comal comas combe combs comer comes ' +
    'comix commy compo comps compt comte coned cones coney conge congo conin conks conky conns conte ' +
    'conto conus cooed cooee cooer cooey coofs cooks cooky cools cooly coomb coops coopt coots copal ' +
    'copay coped copen coper copes copra corby cords cored corer cores coria corks corky corms corns ' +
    'cornu corse cosec coses coset cosey cosie costa coste costs cotan coted cotes cotta coude coups ' +
    'couth coved coves covey covin cowed cowls cowry coxae coxal coxed coxes coyed coyer coyly coypu ' +
    'cozen cozes cozey cozie craal crabs crags crake crams crape craps craws credo creel crees creme ' +
    'crepy crews cribs crick cried crier cries crine cripe croci crocs croft cronk crops crore croup ' +
    'crows croze cruck cruds cruet crump cruor crura cruse crwth cubby cubeb cubed cuber cubes cuddy ' +
    'cuffs cuifs cuing cuish cukes culch culet culex culls cully culms culpa culti cults cupel cuppa ' +
    'cuppy curbs curch curds curdy cured curer cures curet curfs curia curie curls curns currs curst ' +
    'cusec cusks cusps cusso cutch cuter cutes cutey cutin cutis cutty cutup cyano cyans cycad cycas ' +
    'cyclo cyder cylix cymae cymar cymas cymes cymol cysts cyton czars daces dadas dados daeva daffs ' +
    'dagga dahls dales daman damar dames damns damps dangs danio darbs dared darer dares daric darks ' +
    'darns darts dashi dashy dated dater dates datos datto datum daube daubs dauby dauts daven davit ' +
    'dawed dawen dawks dawns dawts dazed dazes deads deair deals deans dears deary deash deave debag ' +
    'debar debts debus debye decks decos dedal deeds deedy deems deeps deers deets defat defis defog ' +
    'degas degum deice deils deism deist deked dekes dekko deled deles delfs delft delis dells delly ' +
    'demes demit demob demos demur denar denes dents deoxy derat deray derma derms derry desex desks ' +
    'devas devel devon dewan dewar dewax dewed dexes dexie dhaks dhals dhobi dhole dhoti dhows dhuti ' +
    'dials diazo diced dicer dices dicky dicot dicta dicty didie didos didst diene diets dight diked ' +
    'diker dikes dikey dills dilly dimer dimes dinar dined dines dinge dings dinks dinky dints diols ' +
    'dippy dipso direr dirks dirls dirts disci discs dishy disks disme ditas dites ditsy ditzy divas ' +
    'dived dives diwan dixie dixit dizen djinn djins doats dobby dobie dobla dobra dobro docks dodos ' +
    'doers doest doeth doffs doges dogey doggo dogie doits dojos dolce dolci doled doles dolls dolma ' +
    'dolor dolts domal domed domes domic donas donee donga dongs donna donne donsy dooly dooms doomy ' +
    'doors doozy dopas doped doper dopes dorks dorms dormy dorps dorrs dorsa dorty dosed doser doses ' +
    'dotal doted doter dotes douce douma doums doura doven doves dowed dower dowie downs dowse doxie ' +
    'doyen doyly dozed dozer dozes drabs draff drags drail drams drats drave draws drays drear dreck ' +
    'dreed drees dregs dreks drest dribs dried drier dries drily drips dript droit drops dropt drouk ' +
    'drubs drugs drums drupe druse duads duals duces ducks ducky ducts duddy duded dudes duels duets ' +
    'duffs duits duked dukes dulia dulls dully dulse dumas dumbo dumbs dumka dumky dumps dunam dunch ' +
    'dunes dungs dungy dunks dunno dunts duomi duomo duped duper dupes duple duppy dural duras dured ' +
    'dures durns duroc duros durra durrs durst durum dusks dusts dutch dwine dyads dyers dynel dynes ' +
    'eagre eared earls earns eased eases easts eaved eaves ebbed ebbet ebons eched eches echos eclat ' +
    'ecrus edema edged edger edges edify edile edits educe educt effed egads egers egest eggar egged ' +
    'egger eider eidos eikon eking elain eland elans elemi elide elint eloin elute elver elves embar ' +
    'embay embow embus emeer emend emery emeus emirs emits emmer emmet emyde emyds enate ended ender ' +
    'endue enema enoki enols enorm enows enrol ensky entia enure envoi enzym eosin epact epees ephah ' +
    'ephas ephod ephor epics epode equid ergot erica ernes erose erred erses eruct erugo ervil escar ' +
    'escot eskar esker esses estop etape ethyl etnas etude etuis etwee etyma euros evens evert evils ' +
    'evite ewers exams exeat execs exine exits exons expos exurb eyers eying eyras eyres eyrie eyrir ' +
    'faced facer faces facia facts faddy faded fader fades fadge fados faena faery faffs fails fairs ' +
    'faked faker fakes fakey fakir falls famed fames fanes fanga fango fangs fanny fanon fanos fanum ' +
    'faqir farad farci farcy fards fared farer fares farle farls farms faros farts fasts fated fates ' +
    'fatly fatso fatty fatwa faugh fauld fauns fauve favas faves favus fawns fawny faxed faxes fayed ' +
    'fayer fayre fazed fazes fears fease feats feaze fecal feces fecit fecks feeds feels feeze feist ' +
    'felid fella fells felly felts femes femme fends fenny feods feoff feres feria ferly fermi ferns ' +
    'ferny fesse fests fetas feted fetes fetor feuar feuds feued feyer feyly fezes fiars fiats fibre ' +
    'fices fiche fichu ficin ficus fidge fidos fiefs fifed fifer fifes filar filed filer files filet ' +
    'fille fillo fills films filos filum finds fined finer fines finis finks finny finos fiord fique ' +
    'fired firer fires firms firns firry firth fiscs fists fitch fitly fiver fives fixed fixes fixit ' +
    'fjeld flabs flack flags flams flamy flans flaps flats flaws flawy flaxy flays fleam fleas fleer ' +
    'flees flews fleys flics flied flies flips flite flits flocs floes flogs flong flops flory flota ' +
    'flows flubs flued flues fluky flump fluor fluty fluyt flyte foals foams foehn fogey fogie fohns ' +
    'foils foins folds folia folic folie folks folky fonds fondu fonts foods fools foots footy foram ' +
    'forbs forby fordo fords fores forks forky forme forms forts fossa fosse fouls fourb fours fovea ' +
    'fowls foxed foxes frack frags fraps frass frats frays freed freer frees fremd frena frere frets ' +
    'fried frier fries frigs frise frith frits fritt fritz frize froes frogs frons frore frosh frows ' +
    'frugs fubsy fucus fuels fugal fuggy fugio fugle fugus fujis fulls fumed fumer fumes fumet fundi ' +
    'funds fungo funks furan furls furze furzy fused fusee fusel fuses fusil fusty fuzed fuzee fuzes ' +
    'fuzil fyces fykes fytte gaddi gadid gadis gaffs gaged gager gages gains gaits galah galas galax ' +
    'galea gales galls gally galop gamas gamay gamba gambe gambs gamed games gamey gamic gamin gammy ' +
    'gamps ganef ganev gangs ganja ganof gaols gaped gaper gapes gappy garbs garni garth gases gasps ' +
    'gasts gated gater gates gator gauds gault gaums gaurs gauss gavot gawks gawps gawsy gayal gayer ' +
    'gayly gazar gazed gazer gazes geans gears gecks geeks geest gelds gelee gelid gelts gemma gemmy ' +
    'gemot genes genet genic genii genip genoa genom genro gents genua geoid gerah germs germy gesso ' +
    'geste gests getas geums ghast ghats ghaut ghazi ghees ghyll gibed giber gibes gifts gigas gighe ' +
    'gigot gigue gilds gills gilly gilts gimel gimme gimps gimpy ginks ginny gipon gipsy girds girls ' +
    'girly girns giron giros girsh girts gismo gists gites giver gives glace glads glady glair glans ' +
    'glary glazy gleba glebe glede gleds gleed gleek glees gleet glens gleys glial glias gliff glime ' +
    'glims gloam globs glogg gloms glops glost glout glows gloze glued gluer glues glugs glume gluon ' +
    'gluts gnarr gnars gnats gnawn gnaws goads goals goats goban gobos godet goers gogos golds golem ' +
    'golfs gombo gonad gonef gongs gonia gonif gonna gonof gonzo goods goofs goons goony goops goopy ' +
    'goosy gopak goral gored gores gorps gorsy goths gotta gouts gouty gowan gowds gowks gowns goxes ' +
    'graal grabs grads grama gramp grams grana grans grapy grays greed greek grees grego greys gride ' +
    'grids griff grift grigs grins griot grips gript gripy grist grith grits groat grogs grosz grots ' +
    'grows grubs grues grume grump guaco guans guars gucks gudes guffs guids guiro gulag gular gulas ' +
    'gules gulfs gulfy gulls gulps gulpy gumma gunge gungy gunks gunky gunny gurge gurry gursh gurus ' +
    'gussy gusts gutta gutty guyed guyot gybed gybes gyral gyred gyres gyron gyros gyrus gyved gyves ' +
    'haafs haars habus hacek hacks hadal haded hades hadji hadst haems haets hafis hafiz hafts hahas ' +
    'haika haiks hails hairs hajes hajis hajji hakes hakim halal haled haler hales halid hallo halls ' +
    'halma halms halon halos halts halva hamal hames hamza hance hands hangs hanks hanky hansa hanse ' +
    'hants haole hapax haply hards hared harem hares harks harls harms harps harry harts hasps hated ' +
    'hates haugh haulm hauls haute haver haves hawed hawks hawse hayed hayer hazan hazed hazer hazes ' +
    'heads heals heaps hears heats hecks heder hedgy heeds heels heeze hefts heigh heils heirs helio ' +
    'hells helms helos helot helps helve hemal hemes hemic hemin hemps hempy henge henry hents herbs ' +
    'herby herds heres herls herma herms herns heros herry hests heths heuch heugh hewed hewer hexad ' +
    'hexed hexer hexes hexyl hicks hided hider hides highs hight hijab hiked hikes hilar hillo hills ' +
    'hilts hilum hilus hinds hinny hints hippy hired hirer hires hissy hists hived hives hoagy hoars ' +
    'hoary hobos hocks hocus hodad hoers hogan hoggs hoick hoise hoked hokes hokku hokum holds holed ' +
    'holes holey holks holla hollo holms holts homed homes honan honda honed honer hones hongs honks ' +
    'hooch hoods hoody hooey hoofs hooka hooks hooly hoops hoots hooty hoped hoper hopes hoppy horah ' +
    'horal horas horme horns horny horst horsy hosed hosel hosen hoses hosta hosts hotch hough houri ' +
    'hours howes howff howfs howks howls hoyas hoyle hucks huffs huger hulas hulks hulky hullo hulls ' +
    'humic humps humpy hunks hunts hurds hurls hurly hurst hurts husks huzza hydro hying hylas hymen ' +
    'hymns hyoid hyped hypes hypha hypos hyrax hyson iambi iambs ichor icier icker icons ictic ictus ' +
    'ideas idiot idled idles idols idyls iglus ihram ikats ikons ileac ileal ileum ileus iliac iliad ' +
    'ilial ilium iller imago imams imaum imbed imide imido imids imine imino immix imped impis inapt ' +
    'inarm inbye incog incus indie indol indow indri indue infix infos infra ingle inion inked inker ' +
    'inkle inned innit inter intis intro inure inurn invar iodic iodid iodin iotas irade irids iring ' +
    'irked iroko irone irons isbas isled isles issei istle items ither ivied ivies ixias ixora ixtle ' +
    'izard izars jabot jacal jacks jacky jaded jades jager jaggs jaggy jagra jails jakes jalap jalop ' +
    'jambe jambs jammy janes janty japan japed japer japes jarls jatos jauks jaups javas jawan jawed ' +
    'jeans jebel jeeps jeers jefes jehad jehus jells jemmy jenny jerid jerks jerry jesse jests jetes ' +
    'jeton jibbs jibed jiber jibes jiffs jihad jills jilts jimpy jingo jinks jinni jinns jisms jived ' +
    'jiver jives jivey jnana jocko jocks joeys johns joins joked jokes jokey joles jolts jolty jones ' +
    'joram jorum jotas jotty joual jouks jowar jowed jowls jowly joyed jubas jubes judas judos jugal ' +
    'jugum jujus juked jukes jumps junco junks junky junto jupes jupon jural jurat jurel justs jutes ' +
    'jutty kabab kabar kabob kadis kagus kaiak kaifs kails kains kakas kakis kalam kales kalif kalis ' +
    'kalpa kames kamik kanas kanes kanji kanzu kaons kapas kaphs kappa karat karns karoo karst karts ' +
    'kasha katas kauri kaury kavas kayos kbars kebar kebob kecks kedge keefs keeks keels keens keeps ' +
    'keets keeve kefir keirs kelep kelim kelly kelps kelpy kemps kempt kenaf kench kendo kenos kente ' +
    'kepis kerbs kerfs kerne kerns kerry ketch ketol kevel kevil kexes keyed khadi khafs khans khaph ' +
    'khats kheda kheth khets khoum kiang kibbe kibbi kibei kibes kibla kicks kicky kiddy kiefs kiers ' +
    'kilim kills kilns kilos kilts kilty kinas kinda kinds kines kings kinin kinks kinky kinos kirks ' +
    'kirns kissy kists kited kiter kites kithe kiths kivas kiwis klong kloof kluge knaps knars knaur ' +
    'kneed knees knish knits knobs knops knosp knots knout knows knurl knurs koans kobos koels kohls ' +
    'koine kolas kolos konks kooks kopek kophs kopje koppa korai korat korma korun koses kotos kotow ' +
    'kraal kraft krait kreep krona krone kroon krubi kudus kugel kukri kulak kumys kurta kurus kusso ' +
    'kvass kyack kyaks kyars kyats kyles kylix kyrie kytes kythe laari labia labra laced lacer laces ' +
    'lacey lacks laded lader lades laevo lagan lahar laich laics laigh laird lairs laith laity laked ' +
    'laker lakes lakhs lalls lamas lambs lamby lamed lamer lames lamia lamps lanai lands lanes lapin ' +
    'lapis lards lardy laree lares laris larks larky larum lased lases lasts lated laten lathi laths ' +
    'lathy latke lauan lauds laura lavas laved laver laves lawed lawns lawny laxer laxly layed layup ' +
    'lazar lazed lazes leads leady leafs leaks leans leant leaps lears leary leavy leben ledgy leeks ' +
    'leers leets lefts leger leges lehrs lehua leman lemma lemme lends lenes lenis lenos lense lento ' +
    'leone lepta letch lethe letup leuds levin lewis lexes lexis liana liane liang liard liars liber ' +
    'libra libri lichi licht licit licks lidar lidos liens liers lieus lieve lifer lifts ligan liger ' +
    'liked liker likes lilos lilts liman limas limba limbi limbs limby limed limen limes limey limns ' +
    'limos limpa limps linac lindy lined lines liney linga lings lingy linin links linky linns linos ' +
    'lints linty linum lions lipin lippy liras lirot lisle lisps lists litai litas litho litre lived ' +
    'lives livre llano loach loads loafs loams loans lobar lobed lobes lobos lochs locks locos locum ' +
    'loden lodes loess lofts logan loges loggy logia logoi logon logos loins lolls lolly longe longs ' +
    'looby looed looey loofa loofs looie looks looms loons loony loops loots loped loper lopes loppy ' +
    'loral loran lords lores loris lorry losel loses lossy lotah lotas lotic lotos lotte lough louie ' +
    'louis loupe loups lours loury louts lovat loved loves lovey lowed lowes lowse loxed loxes luaus ' +
    'lubed lubes lubra luces lucks lucre ludes ludic luffa luffs luged luger luges lulls lulus lumen ' +
    'lumps lunas lunes lunet lungi lungs lunks lunts lupin lupus lured lurer lures lurex lurgy lurks ' +
    'lushy lusts lusty lusus lutea luted lutes luxes lweis lyard lyart lyase lycea lycee lynch lyres ' +
    'lysed lyses lysin lysis lyssa lytic lytta maars mabes maced macer maces mache machs macks macle ' +
    'macon madre mafia mafic mages magot magus mahoe maids maile maill mails maims mains mairs maist ' +
    'makar makes makos malar males malic malls malms malmy malts malty mamas mamba mamey mamie mamma ' +
    'manas manat maned manes manky manos manse manta manus maqui maras marcs mares marge maria marka ' +
    'marks marls marly marse marts marvy maser mashy masks massa masse massy masts mated mater mates ' +
    'matey maths matin matts matza mauds mauls maund mauts mavie mavin mavis mawed maxed maxes maxis ' +
    'mayan mayas mayed mayos mayst mazed mazer mazes mbira meads meals means meany meats mecca medii ' +
    'meeds meets meiny melds melic mells melts memes memos menad mends mensa mense menta menus meous ' +
    'meows merde merer meres merks merle merls mesas meshy mesic mesne meson meted metes meths metic ' +
    'metis metre mewed mewls mezes mezzo miaou miaow miasm miaul micas miche micra middy midis miens ' +
    'miffs miffy miggs miked mikes mikra mikva milch miler miles milfs milia milks mille mills milos ' +
    'milpa milts milty mimed mimeo mimer mimes minae minas mincy minds mined mines mingy minim minis ' +
    'minke minks minny mints mired mires mirex mirin mirks mirky mirza misdo mises misos missy mists ' +
    'miter mites mitis mitre mitts mixed mixes mixup mizen mneme moans moats mocks modes modus moggy ' +
    'mohel mohur moils moira moire mojos mokes molal molas molds moles molls molly molto molts momes ' +
    'momma momus monad monas monde mondo mongo monie monks monos monte moods mooed moola mools moons ' +
    'moony moors moory moots moped moper mopes mopey morae moras morel mores morns moron morro morse ' +
    'morts mosks mosso moste mosts motes motet motey moths mothy motte motts mouch moues mould moult ' +
    'moved moves mowed moxas moxie mozos mucid mucin mucks mucor mucro mucus mudra muffs mufti muggs ' +
    'muhly mujik mulct muled mules muley mulla mulls multi mumms mumps mumus mungo munis muons muras ' +
    'mured mures murex murid murks murra murre murrs murry musca mused muser muses musks mussy musth ' +
    'musts mutch muted muter mutes muton mutts muzak muzzy myall mynah mynas myoid myoma myope myopy ' +
    'mysid myths mythy naans nabes nabis nabob nacre nadas naevi naggy naiad naifs nails naira naker ' +
    'nakfa naled named namer names nanas napes nappe nappy narco narcs nards nares naric naris narks ' +
    'narky natch nates navar naves navvy nawab neaps nears neath neats necks needs neems neeps negus ' +
    'neifs neist nelly nemas neons neper neral nerds nerol nerts nertz nests netop netts netty neuks ' +
    'neume neums neves nevus newel newer newie newsy newts ngwee nicad nicer nicks nicol nidal nided ' +
    'nides nidus nieve niffy nighs nihil nills nimbi nimby nines ninny ninon nipas nisei nisus niter ' +
    'nites nitid niton nitre nitro nitty nival nixed nixes nixie nizam nobby nocks nodal noddy nodes ' +
    'nodus noels noggs nohow noils noily noirs nolos nomas nomen nomes nomoi nomos nonas nonce nones ' +
    'nonet nonyl nooks noons nopal noria noris norms nosed noses nosey notal noted noter notes notum ' +
    'nouns novae novas noway nowts nubby nubia nucha nuder nudes nudie nudzh nuked nukes nulls numbs ' +
    'numen nurds nurls nutsy nyala oakum oared oases oasts oaten oater oaths oaves obeah obeli obeys ' +
    'obias obits objet oboes obole oboli obols ocher ochre ochry ocker ocrea octad octal octan octyl ' +
    'oculi odder odeon odeum odist odium odors odour odyle odyls oecus offed ofter ogams ogeed ogees ' +
    'ogham ogive ogled ogler ogles ogres ohias ohing ohmic oidia oiled oiler oinks okays okehs okras ' +
    'oleic olein oleos oleum olios ollas ology omasa omber ombre omens omers omits onery onium ontic ' +
    'oohed oomph oorie ootid oozed oozes opahs opals opens oping opium opsin opted orach orals orang ' +
    'orbed orcas orcin ordos oread orgic oribi oriel orles orlop ormer ornis orpin orris ortho orzos ' +
    'osier osmic osmol ossia ostia ottar ottos ouphe ouphs ourie ousel ousts outby outed outgo outre ' +
    'outta ouzel ouzos ovals ovary ovate ovens overs ovine ovoid ovoli ovolo ovule owing owned owsen ' +
    'oxeye oxids oxime oxims oxlip oxter oyers pacas paced paces pacey pacha packs pacts paddy padis ' +
    'padle padri paean paeon paged pages pagod paiks pails pains pairs paisa paise palea paled paleo ' +
    'paler pales palet palls pally palms palmy palpi palps palsy pampa pandy paned panes panga pangs ' +
    'panne pansy panto pants panty papas papaw pappi pappy paras pardi pards pardy pared pareo parer ' +
    'pares pareu parge pargo paris parks parky parle parol parrs parts parve parvo paseo pases pasha ' +
    'pashm passe pasts pated paten pater pates paths patin patly pavan paved paver paves pavid pavin ' +
    'pavis pawed pawer pawky pawls pawns paxes payed payor peage peags peaks peaky peals peans pears ' +
    'peart pease peats peaty peavy pebas pechs pecks pecky pedes pedro peeks peels peens peeps peers ' +
    'peery peins peise pekan pekes pekin pekoe peles pelfs pelon pelts pends penes pengo penis penna ' +
    'penni peons pepla pepos perdu perdy perea peris perks perms perry perse pervs pesos pests pesty ' +
    'peter petit petti petto pewee pewit phage pheon phial phish phlox phono phons phots phpht phuts ' +
    'phyla phyle pians pibal pical picas picks picot picul piers pieta pigmy piing pikas piked piker ' +
    'pikes pikis pilar pilau pilaw pilch pilea piled pilei piles pilis pills pilus pimas pimps pinas ' +
    'pined pines piney pingo pings pinko pinks pinna pinny pinon pinot pinta pints pinup pions pipal ' +
    'piped pipes pipet pipit pique pirns pirog pisco pisos piste pitas piths pitta pixes plack plage ' +
    'plans plash plasm plats platy playa plays pleas plebe plebs plena plews plica plied plier plies ' +
    'plink ploce plods plonk plops plots plotz plows ploys plugs plums plumy plyer pocks pocky poddy ' +
    'podgy podia poems poesy poets pogey pogge poilu poind poked pokes pokey poled poler poles polis ' +
    'polls polos polys pomes pommy pomps ponce poncy ponds pones pongs poods pooed poohs pooka pools ' +
    'poons poops poori popes poppa popsy popup pored porer pores porgy porks porky ports posed poses ' +
    'posts potsy potto potty pouff poufs poult pours pouts pouty poxed poxes poyou praam prahu prams ' +
    'prana prang praos prase prate prats praus prays preed prees preps presa prese prest prexy preys ' +
    'prick pricy pried prier pries prigs prill prima primi primo prims prink prion prise priss proas ' +
    'prods proem profs progs prole proms props proso pross prost prosy prows pruta pryer pseud pshaw ' +
    'psoae psoai psoas psych pubes pubic pubis puces pucka pucks pudic puffs puggy pujah pujas puked ' +
    'pukes pukka pulas puled puler pules pulik pulis pulls pulps pumas pumps punas pungs pungy punka ' +
    'punks punky punny punto punts punty pupae pupal pupas purda purer purin puris purls purrs pursy ' +
    'puses puton putti putto putts pwned pygmy pyins pyoid pyran pyres pyric pyxes pyxie pyxis pzazz ' +
    'qaids qanat qibla qophs quads quags quais quaky quale quant quare quasi quass quate quays quean ' +
    'queer quern queys quids quiff quins quint quips quipu quire quirt quits quods quoin quoit quoth ' +
    'qursh rabat rabic raced races racks racon radii radix raffs rafts ragas raged ragee rages ragga ' +
    'raggy ragis raias raids rails rains rajah rajas rajes raked rakee raker rakes rakis rales ralph ' +
    'ramee ramet ramie rammy ramps ramus rance rands randy ranee rangy ranid ranis ranks rants raphe ' +
    'rared rarer rares rased raser rases rasps ratal ratan ratch rated ratel rater rates rathe ratos ' +
    'raved raver raves ravin rawer rawin rawly raxed raxes rayah rayas rayed razed razee razer razes ' +
    'readd reads reals reams reaps rearm rears reata reave rebar rebbe rebec rebid rebop rebuy recce ' +
    'recks recon recta recti recto recut redan redds reded redes redia redid redip redly redon redos ' +
    'redox redry redub redux redye reeds reefs reefy reeks reeky reels reest reeve refed refel refix ' +
    'refly refry reges regex regma regna rehem reifs reify reink reins reive rejig rekey relet relit ' +
    'reman remap remet remex rends renes renig renin rente rents reoil reorg repeg repin repos repot ' +
    'repps repro reran rerig resat resaw resay resee resew resid resit resod resow rests retag retax ' +
    'retem retia retie revet rewan rewax rewed rewet rewin rewon rexes rheas rheum rhomb rhumb rhyta ' +
    'rials riant riata ribby ribes riced ricer rices ricin ricks rides ridgy riels rifer riffs rifts ' +
    'riled riles riley rille rills rimed rimer rimes rinds rings rinks rioja riots riped riper ripes ' +
    'rises rishi risks risus rites rived riven rives riyal roads roams roans roars robed robes roble ' +
    'rocks roger roils roily roles rolfs rolls roman romeo romps ronde rondo roods roofs rooks rooky ' +
    'rooms roose roots rooty roped roper ropes ropey roque rosed roses roset rosin rotas rotch rotes ' +
    'rotis rotls rotos rotte rouen roues roups roupy roust routh routs roved roven roves rowan rowed ' +
    'rowel rowen rowth ruana rubel rubes rubus ruche rucks rudds ruder ruers ruffe ruffs rugae rugal ' +
    'ruing ruins ruled rules rumal rumen rumps runes rungs runic runts runty ruses rushy rusks rusts ' +
    'ruths rutin rutty ryked rykes rynds ryots sabed sabes sabin sabir sabot sabra sabre sacks sacra ' +
    'sades sadhe sadhu sadis saeta safer safes sagas sager sages saggy sagos sagum sahib saice saids ' +
    'saiga sails sains saith sajou saker sakes sakis salal salep sales salic sally salmi salol salpa ' +
    'salps salts sambo samek sames samey samps sands saned saner sanes sanga sangh sangs santo sapid ' +
    'sapor saran sards saree sarin saris sarks sarky sarod saros sasin sated satem sates satis satyr ' +
    'sauch saugh sauls sault saury saute saved saves savin savoy sawed sawer saxes sayer sayid sayst ' +
    'scabs scads scags scall scams scans scape scarp scars scart scats scatt scaup scaur scena scend ' +
    'schav schmo schul schwa scops scots scows scrag scree scrim scrip scrod scudi scudo scuds sculk ' +
    'scull sculp scums scups scurf scuta scute scuts seals seams seamy sears seats sebum secco sects ' +
    'seder sedge sedgy sedum seeds seeks seels seely seems seeps seepy seers segni segno segos seifs ' +
    'seine seise seism selah selfs selle sells selva semen semes semis sends sengi senna senor sensa ' +
    'sente senti sepal sepic sepoy septa septs serac serai seral sered serer seres serfs serin serow ' +
    'serry servo setae setal seton setts sewan sewar sewed sexed sexes sexto sexts shads shags shahs ' +
    'shako shalt shaly shams sharn shaul shawm shawn shaws shays sheal sheas sheds shend shent sheol ' +
    'sherd shewn shews shied shiel shier shies shily shims shins ships shirr shist shiva shive shivs ' +
    'shlep shoat shoed shoer shoes shogs shoji shool shoon shoos shops shorl shorn shote shots shott ' +
    'shows shoyu shris shtik shuln shuls shuns shute shuts shyer shyly sials sibbs sibyl sices sicko ' +
    'sicks sided sides sieur sifts sighs sigil signs sikas siker sikes silds silex silks sills silos ' +
    'silts silty silva simar simas simba simps sines sings sinhs sinks siped sipes sired siree sires ' +
    'sirra sirup sisal sises sissy sited sites situp situs siver sixes sixmo sixte sizar sized sizer ' +
    'sizes skags skald skats skean skeed skeen skees skeet skegs skelm skelp skene skeps skews skids ' +
    'skied skies skiey skimo skims skink skins skint skips skirl skirr skite skits skive skoal skosh ' +
    'skuas skyed skyey slabs slags slams slank slaps slats slaty slave slaws slays sleds slews slier ' +
    'slily slims slipe slips slipt slits slobs sloes slogs sloid slojd slops slots slows sloyd slubs ' +
    'slued slues sluff slugs slums slurb slurs slyer slype smalt smarm smaze smeek smerk smews smogs ' +
    'smoko smolt smote smuts snags snaky snaps snark snash snath snaws sneap sneck sneds snell snibs ' +
    'snick snips snits snobs snogs snood snook snool snoot snots snows snubs snuck snugs snyes soaks ' +
    'soaps soars soave socko socks socle sodas soddy sodic sodom sofar sofas softa softs soils sojas ' +
    'sokes sokol solan soldi soldo soled solei soles solon solos solum solus somas sonde sones songs ' +
    'sonly sonny sonsy sooey sooks sooth soots sophs sophy sopor soppy soras sorbs sords sorel sorer ' +
    'sores sorgo sorns sorta sorts sorus soths sotol sough souks souls soups sours souse sowar sowed ' +
    'sower soyas soyuz sozin spacy spado spaed spaes spahi spail spait spake spale spall spams spang ' +
    'spank spans spars spats spays spean specs speel speer speil speir spelt speos sperm spews spica ' +
    'spied spier spies spiff spile spilt spins spirt spiry spits spitz spivs splay spode spook spoor ' +
    'spots sprag sprat sprit sprog sprue sprug spuds spued spues spume spumy spunk spurs sputa squab ' +
    'squeg squib sruti stabs stade stags stagy staig stane stang staph stars stats stays stead steek ' +
    'stela stele stems steno steps stere stets stews stich stied sties stile stime stimy stipe stirk ' +
    'stirp stirs stoae stoai stoas stobs stogy stoma stook stope stops stopt stoss stoup stour stowp ' +
    'stows stree stria strop strow stroy stubs studs stull stums stuns stupa stupe sturt styed styes ' +
    'styli stymy subah subas suber sucks sucre sudds sudor suers suets suety sughs suing suint suits ' +
    'sulci sulfa sulfo sulks sulus summa sumos sumps sunna sunns sunup supes supra surah sural suras ' +
    'surds surer surfs surfy surgy surra sutra sutta swabs swage swags swail swain swale swami swamy ' +
    'swang swans swaps sward sware swarf swart swash swats sways swede sweer swigs swims swink swiss ' +
    'swith swive swizz swobs swops swots swoun sycee syces sykes sylis sylph sylva synch syncs synod ' +
    'synth syphs syren sysop taber tabes tabid tabla tabor tabun tabus taces tacet tache tachs tacks ' +
    'tacos tacts taels tafia tahrs taiga tails tains tajes takas takes takin talar talas talcs taler ' +
    'tales talks talky taluk talus tamal tamed tames tamis tammy tamps tangs tanka tanks tansy tanto ' +
    'tapas taped tapes tapis tared tares targe tarns taroc tarok taros tarps tarre tarsi tarts tarty ' +
    'taser tasks tasse tatar tater tates tauts tawed tawer tawie tawse taxed taxer taxes taxis taxon ' +
    'taxus tayra tazza tazze teaks teals teams tears teats techs techy tecta teels teems teens teffs ' +
    'tegua teiid teind telae teles telex telia telic tells telly teloi telos tempi temps tench tends ' +
    'tenge tenia tenno tenon tents tenty tepal tepas tepee tepoy terai terce terga terms terne terns ' +
    'terra terry tesla testa tests teths tetra teuch teugh tewed texas texts thack thane tharm thaws ' +
    'thebe theca thees thegn thein thens therm thews thewy thill thine thins thiol thirl thole thong ' +
    'thoro thorp thous thraw thrip thrum thuds thugs thuja thunk thurl thuya thymi thymy tical ticks ' +
    'tided tides tiers tiffs tigon tikes tikis tilak tilde tiled tiler tiles tills tilth tilts timed ' +
    'times tinct tinea tined tines tings tints tipis tippy tired tires tirls tiros titch titer titis ' +
    'titre toads toeas toffs toffy tofts tofus togae togas togue toile toils toits tokay toked toker ' +
    'tokes tolan tolar tolas toled toles tolls tolly tolus tolyl toman tombs tomes tommy tondi tondo ' +
    'toned tones toney tonga tongs tonus tools toons toots toped topee toper topes tophe tophi tophs ' +
    'topis topoi topos toque torah toras torcs tores toric torii toros torot torrs torse torsi torsk ' +
    'torts toted toter totes tours touse touts towed towie towns towny toyed toyer toyon toyos tragi ' +
    'traik trams trank tranq trans traps trapt trass trave trays treed treen trees treks tress trets ' +
    'trews treys triac trice tried trier tries trigo trigs trims trine triol trios trips troak troat ' +
    'trock trode trois troke tromp trona trone trooz troth trots trows troys trued truer trues trugs ' +
    'trull tryma tsade tsadi tsars tsked tsuba tubae tubal tubas tubed tubes tucks tufas tuffs tufts ' +
    'tufty tules tumid tumor tumps tunas tuned tunes tungs tunny tupik tuple tuque turbo turds turfs ' +
    'turfy turks turns turps tushy tusks tutee tutti tutty tutus tuxes tuyer twaes twain tween twerk ' +
    'twier twigs twink twins twiny twirp twits twixt twyer tyees tyers tykes tyned tynes typal typed ' +
    'types typey typic typos typps tyred tyres tyros tythe tzars uhlan ukase ulama ulans ulema ulnad ' +
    'ulnae ulnar ulnas ulpan ulvas umbel umber umbos umiac umiak umiaq umped unais unapt unarm unary ' +
    'unaus unban unbar unbid unbox uncia uncos uncoy uncus undee undid unfed unfix ungot unhat unhip ' +
    'units unjam unlay unled unlet unman unmet unmew unmix unpeg unpen unrig unrip unsay unset unsew ' +
    'unsex unwit unwon upbow upbye updos updry uplit upped uraei urare urari urase urate urbia ureal ' +
    'ureas uredo ureic urged urger urges urial urine ursae users usnea usque uteri utile uveal uveas ' +
    'uvula vacua vagal vagus vails vairs vakil vales valse vamps vampy vanda vaned vanes vangs vaped ' +
    'vapes varas varia varix varna varus varve vasal vases vasts vasty vatic vatus veals vealy vedic ' +
    'veena veeps veers veery veges vegie veils veins veiny velar velds veldt velum venae vends venge ' +
    'venin vents verbs verey versa verso verst verts vertu vesta vests vetch veter vexed vexer vexes ' +
    'vexil vials viand vibes viced vices vichy viers views viewy vigas viler villi vills vimen vinal ' +
    'vinas vinca vined vines vinic vinos viols vireo vires virga virid virls virtu visas vised vises ' +
    'vitae vitta vivas vixen vizir vizor voces vodun vogie voids voile volar voled voles volta volte ' +
    'volti volts volva vomer vomit voted votes vouge vowed vower vroom vrouw vrows vuggs vuggy vughs ' +
    'vulgo vulva wacke wacko wacks waddy waded wades wadge wadis waffs wafts waged wages wahoo waifs ' +
    'wails wains wairs waits waked waker wakes waled waler wales walks walla walls wally wames wamus ' +
    'wands waned wanes waney wanly wanna wants wards wared wares warks warms warns warps warts washy ' +
    'wasps waspy wasts watap watts waugh wauks wauls waved waves wavey wawls waxed waxer waxes wazoo ' +
    'weald weals weans wears webby weber wecht wedel wedgy weeds weeks weens weeny weeps weest weets ' +
    'wefts weirs wekas welch welds wells welly welsh welts wench wends wenny wersh wests wetly whamo ' +
    'whams whang whaps whats whaup wheal wheen wheep whelk whelm whens whets whews wheys whids whigs ' +
    'whims whins whips whipt whirr whirs whish whist whits whity whizz whomp whoof whops whorl whort ' +
    'whoso whump whups wicks widdy wider wides wifed wifes wifty wigan wiggy wight wikis wilco wilds ' +
    'wiled wiles wills willy wilts wimps winds wined wines winey wings wingy winks winos winze wiped ' +
    'wipes wired wirer wires wirra wised wisen wises wisha wisps wists witan wited wites withe withy ' +
    'wived wiver wives wizen wizes woads woald wodge woful wolds wolfs wombs womby wonks wonky wonts ' +
    'woods wooed wooer woofs wools wooly woops woosh words works worms worts wowed wrack wrang wraps ' +
    'wrapt wrens wrick wried wrier wries writs wroth wryer wurst wussy wyled wyles wynds wynns wyted ' +
    'wytes xebec xenia xenic xeric xerox xerus xylan xylem xylol xylyl xysti xysts yacks yaffs yager ' +
    'yagis yahoo yaird yakka yamen yamun yangs yanks yapok yapon yappy yards yarer yarns yauds yauld ' +
    'yaups yawed yawls yawns yawps yeahs yeans years yecch yechs yechy yeggs yelks yells yelps yenta ' +
    'yente yerba yerks yeses yetis yetts yeuks yeuky yikes yills yince yipes yirds yirrs yirth ylems ' +
    'yobbo yocks yodhs yodle yogas yogee yoghs yogic yogin yogis yoked yokes yolks yolky yomim yonic ' +
    'yonis yonks yores yourn yours youse yowed yowes yowie yowls yuans yucas yucch yucks yugas yukky ' +
    'yulan yules yupon yurta yurts zaire zamia zanza zappy zarfs zaxes zayin zazen zeals zebec zebus ' +
    'zeins zerks zeros zests zetas zibet zills zincs zincy zineb zines zings zingy zinky ziram zitis ' +
    'zizit zlote zloty zoeae zoeal zoeas zombi zonal zoned zoner zones zonks zooid zooks zooms zoons ' +
    'zooty zoril zoris zowie zymes'
  ).split(' ');

  var api = { answers: ANSWERS, guesses: GUESSES };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.WordleWords = api;
})(typeof window !== 'undefined' ? window : this);
