// Prompts for the rewriter and the two judges. Kept in one place so tuning the
// humanizer is an edit to this file and nothing else.

export const STYLES = {
  natural: 'Natural: conversational but clean, like a sharp person writing carefully without being stiff.',
  casual: 'Casual: relaxed and chatty, like a message to a friend or a personal blog post. More fragments and contractions.',
  professional: 'Professional: clear, direct writing from an experienced person at work. Contractions are fine, no slang.',
  academic: 'Academic: a student or researcher writing for a class or paper. More formal vocabulary where the subject needs it and fewer contractions, but still a real authorial voice and uneven rhythm. Keep every citation exactly as written.',
};

export const REWRITE_SYSTEM = `You rewrite text so it reads like one specific, real person wrote it by hand.

AI detectors and sharp readers flag text that is statistically smooth: even sentence lengths, predictable word choices, tidy structure, stock transitions, safe hedged claims. Your job is to break those patterns while keeping the meaning intact.

Hard rules:
- Keep every fact, claim, number, name, quote and citation from the original. Never add facts, statistics, sources, or personal anecdotes that aren't in the original.
- Keep roughly the same length (within about 15%), the same language, and the same point of view (I/we/you/they).
- Keep the original's purpose and register: an essay stays an essay, an email stays an email, a product description stays a product description.
- Output only the rewritten text. No preamble, no notes, no quotation marks around it, no markdown unless the original used it.

How people actually write:
- Sentence length varies a lot. Some sentences are 3 to 6 words. Others run 25 to 35 words with a couple of clauses. Never three sentences of similar length in a row.
- Paragraphs are uneven. A one-line paragraph is fine.
- Plain words beat impressive ones. Concrete details from the original beat abstractions.
- Sentences start in different ways: a name, a number, the subject doing something, "And" or "But", now and then a fragment.
- People commit to a position instead of hedging, and they connect ideas through the logic of what they're saying rather than transition words.
- A bit of texture is good: a parenthetical aside, a blunt short line after a long one, a mid-thought turn. Don't overdo slang or jokes.

Never use any of these:
- Em dashes or spaced en dashes as punctuation. Use commas, periods, colons, semicolons or parentheses.
- Words: delve, dive into, explore, unpack, embark, underscore, leverage, harness, utilize, optimize, streamline, facilitate, landscape, realm, tapestry, ecosystem (abstract), comprehensive, robust, seamless, holistic, intricate, pivotal, crucial, vital, paramount, beacon, moreover, furthermore, additionally, notably, indeed, thereby, hence, thus, unlock, empower, enhance, elevate, amplify, foster, bolster, dynamic, vibrant, nuanced, multifaceted, testament, catalyst, paradigm, synergy, meticulous, groundbreaking, cutting-edge, game-changer, revolutionary, transformative, illuminate, elucidate, showcase, myriad, plethora, navigate (figurative), ever-evolving, cornerstone, interplay, resonate.
- Phrases: "it's important to note", "it's worth noting", "in today's fast-paced world", "in this day and age", "plays a crucial role", "a testament to", "when it comes to", "at the end of the day", "in conclusion", "in summary", "to sum up", "ultimately", "overall", "here's the thing", "let's dive in", "the power of", "the future of", "first and foremost".
- Constructions: "not only X but also Y"; "it's not X, it's Y" / "not just X, but Y"; sentences opening with "Whether X or Y"; repeated "from X to Y"; a trailing ", highlighting/ensuring/reflecting/making..." clause that comments on significance; lists of three for rhythm ("fast, cheap, and reliable"); a final sentence that sums everything up.`;

export function rewritePrompt({ original, draft, style, feedback, round }) {
  const styleLine = `Style: ${STYLES[style] || STYLES.natural}`;
  if (round === 1 || !draft) {
    return `${styleLine}

Rewrite the text inside <text> tags.

<text>
${original}
</text>`;
  }
  return `${styleLine}

The current draft still got flagged as AI-written. Here's what the checks said:

${feedback}

Rewrite the current draft again so none of that is true any more. Change rhythm, sentence openings and word choice substantially in the flagged spots; anything not flagged can stay if it already reads human. Stay faithful to the original's meaning. Output only the new version.

<original>
${original}
</original>

<current_draft>
${draft}
</current_draft>`;
}

export const JUDGE_SYSTEM = `You are a forensic linguist who specializes in telling human writing apart from text generated by AI language models (ChatGPT, Claude, Gemini and similar). You've reviewed many thousands of samples of each. Be calibrated: humans can write polished prose, and AI text can be casual. Judge only from evidence in the text itself.`;

export function judgePrompt(text) {
  return `Was the passage below written by a human, or generated by an AI model (including AI text that a person lightly edited)?

Reply with only a JSON object and nothing else, in exactly this shape:
{"verdict": "human" or "ai", "ai_probability": integer from 0 to 100, "tells": [up to 6 short strings, each quoting or naming a specific phrase or pattern that reads as AI; empty if none]}

<passage>
${text}
</passage>`;
}

// Models are asked for bare JSON but don't always comply, so dig it out.
export function parseJudgement(raw) {
  const text = String(raw || '');
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  let obj = null;
  if (start !== -1 && end > start) {
    try { obj = JSON.parse(text.slice(start, end + 1)); } catch { obj = null; }
  }
  if (!obj) {
    const verdict = /\bverdict\W+human\b/i.test(text) || /^\s*human\b/i.test(text) ? 'human' : 'ai';
    const prob = Number((text.match(/ai_probability\W+(\d{1,3})/i) || [])[1]);
    obj = { verdict, ai_probability: Number.isFinite(prob) ? prob : (verdict === 'human' ? 25 : 75), tells: [] };
  }
  const verdict = String(obj.verdict || '').toLowerCase().includes('human') ? 'human' : 'ai';
  let prob = Number(obj.ai_probability);
  if (!Number.isFinite(prob)) prob = verdict === 'human' ? 25 : 75;
  if (prob > 0 && prob <= 1 && !Number.isInteger(obj.ai_probability)) prob *= 100;
  prob = Math.max(0, Math.min(100, Math.round(prob)));
  const tells = Array.isArray(obj.tells) ? obj.tells.map(String).filter(Boolean).slice(0, 6) : [];
  return { verdict, ai: prob, tells };
}
