import type { Settings } from '@shared/types'
import { type PackFiles, on, opt } from './common'

// "Master Client World Tweaks": a behaviour pack for your own worlds. It does
// nothing until you turn it on for a world in that world's Behavior Packs.
// Uses only the stable @minecraft/server Script API.

export interface WorldTweaksConfig {
  time: { enabled: boolean; value: number; lock: boolean }
  nightVision: boolean
}

export function worldTweaksConfig(s: Settings): WorldTweaksConfig {
  return {
    time: {
      enabled: on(s, 'timechanger'),
      value: Math.round(opt<number>(s, 'timechanger', 'time') ?? 6000),
      lock: opt<boolean>(s, 'timechanger', 'lock') !== false
    },
    nightVision: on(s, 'fullbright') && opt<boolean>(s, 'fullbright', 'nightVision') === true
  }
}

export function wantsWorldTweaks(s: Settings): boolean {
  const c = worldTweaksConfig(s)
  return c.time.enabled || c.nightVision
}

export function worldTweaksScript(c: WorldTweaksConfig): string {
  return `// Generated by Master Client. Your own worlds only.
import { system, world } from '@minecraft/server'

const CONFIG = ${JSON.stringify(c)}

let timeSet = false

system.runInterval(() => {
  if (CONFIG.time.enabled && (CONFIG.time.lock || !timeSet)) {
    world.setTimeOfDay(CONFIG.time.value)
    timeSet = true
  }
  if (CONFIG.nightVision) {
    for (const player of world.getAllPlayers()) {
      // 20s, topped up every 5s, so it never reaches the flicker at the end.
      player.addEffect('night_vision', 400, { amplifier: 0, showParticles: false })
    }
  }
}, 100)
`
}

export function buildBehaviorPack(s: Settings, files: PackFiles): void {
  files.set('scripts/main.js', worldTweaksScript(worldTweaksConfig(s)))
}
