import { createHash } from 'node:crypto'
import type { Settings } from '@shared/types'
import type { PackIds } from '../store'
import { Canvas } from './png'
import { type PackFiles, TEX_DIR, json } from './generators/common'
import { buildHudUi } from './generators/hud'
import { buildVisuals } from './generators/visuals'
import { buildBehaviorPack } from './generators/behavior'
import { packIconPng } from './icon'

export type Version = [number, number, number]

export const RP_FOLDER = 'MasterClient_RP'
export const BP_FOLDER = 'MasterClient_WorldTweaks_BP'
export const MIN_ENGINE: Version = [1, 21, 90]

export interface BuiltPack {
  files: PackFiles
  /** Hash of everything except the manifest, used to decide whether to bump the version. */
  hash: string
}

export function hashFiles(files: PackFiles): string {
  const h = createHash('sha256')
  for (const key of [...files.keys()].sort()) {
    if (key === 'manifest.json') continue
    h.update(key)
    h.update('\0')
    h.update(files.get(key)!)
    h.update('\0')
  }
  return h.digest('hex')
}

export function bump(v: Version): Version {
  return [v[0], v[1], v[2] + 1]
}

/** Every file of the Master Client resource pack except manifest.json. */
export function buildResourceContent(s: Settings): BuiltPack {
  const files: PackFiles = new Map()
  const white = new Canvas(1, 1)
  white.fill([255, 255, 255, 255])
  files.set(`${TEX_DIR}/white.png`, white.toPng())

  const globals: Record<string, unknown> = {}
  buildHudUi(s, files)
  buildVisuals(s, files, globals)
  if (Object.keys(globals).length > 0) files.set('ui/_global_variables.json', json(globals))

  files.set('pack_icon.png', packIconPng(s.appearance.accent))
  return { files, hash: hashFiles(files) }
}

export function resourceManifest(ids: PackIds, version: Version): string {
  return json({
    format_version: 2,
    header: {
      name: 'Master Client',
      description: 'Generated by the Master Client launcher. Changes apply when you rejoin a world or server.',
      uuid: ids.rpHeader,
      version,
      min_engine_version: MIN_ENGINE
    },
    modules: [{ type: 'resources', uuid: ids.rpModule, version }],
    // Declares Vibrant Visuals support so the pack doesn't switch it off, and so
    // lighting/global.json (Full bright) is read.
    capabilities: ['pbr'],
    metadata: { authors: ['Master Client'], generated_with: { master_client: ['1.0.0'] } }
  })
}

export function buildBehaviorContent(s: Settings): BuiltPack {
  const files: PackFiles = new Map()
  buildBehaviorPack(s, files)
  files.set('pack_icon.png', packIconPng(s.appearance.accent, true))
  return { files, hash: hashFiles(files) }
}

export function behaviorManifest(ids: PackIds, version: Version): string {
  return json({
    format_version: 2,
    header: {
      name: 'Master Client World Tweaks',
      description: 'Time changer and night vision from Master Client. For your own worlds only.',
      uuid: ids.bpHeader,
      version,
      min_engine_version: MIN_ENGINE
    },
    modules: [
      { type: 'data', uuid: ids.bpData, version },
      { type: 'script', language: 'javascript', uuid: ids.bpScript, version, entry: 'scripts/main.js' }
    ],
    dependencies: [{ module_name: '@minecraft/server', version: '2.0.0' }],
    metadata: { authors: ['Master Client'] }
  })
}
